development:
  secret_key_base: f18a0a8b41e61d11079c8c29e4afc242d4140337ae7a62b2b496489c45b3192f10bfaf05ff79d5dd7acbed34971b049cbf34f9f7d611038064547247a483ced4

test:
  secret_key_base: 9d2ff9fe737bb100de39a471a55e93927000a806dfcf17b5a44ecc3dba54b0623753cc18f7a4d59bb60d11318cd9dc92ff395f91c829676989ad5a8ef5d7b768

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
